# Generated by Django 5.0.3 on 2024-03-15 21:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMovement',
            fields=[
                ('movement_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of Move')),
                ('quantity', models.IntegerField(verbose_name='Moved Quantity')),
                ('from_location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='inventory_management.location')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.product')),
                ('to_location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='inventory_management.location')),
            ],
        ),
    ]
