# Generated by Django 5.0.3 on 2024-03-11 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmovement',
            name='from_location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='inventory_management.locations'),
        ),
        migrations.AlterField(
            model_name='productmovement',
            name='to_location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='inventory_management.locations'),
        ),
    ]
